/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "outline-variant": "#bec9c2",
        "on-error-container": "#93000a",
        "surface": "#f7f9ff",
        "surface-dim": "#d1dbe8",
        "surface-bright": "#f7f9ff",
        "surface-container-lowest": "#ffffff",
        "surface-container-low": "#edf4ff",
        "surface-container": "#e4effd",
        "surface-container-high": "#dfe9f7",
        "surface-container-highest": "#d9e3f1",
        "surface-variant": "#d9e3f1",
        "on-surface": "#121d26",
        "on-surface-variant": "#3f4944",
        "inverse-surface": "#27313c",
        "inverse-on-surface": "#e8f2ff",
        "outline": "#6f7974",
        "surface-tint": "#176b52",
        "primary": "#00513c",
        "on-primary": "#ffffff",
        "primary-container": "#176b52",
        "on-primary-container": "#9be9c9",
        "inverse-primary": "#89d6b7",
        "secondary": "#4f635c",
        "on-secondary": "#ffffff",
        "secondary-container": "#cfe5dc",
        "on-secondary-container": "#536760",
        "tertiary": "#00513f",
        "on-tertiary": "#ffffff",
        "tertiary-container": "#006c55",
        "on-tertiary-container": "#82edca",
        "error": "#ba1a1a",
        "on-error": "#ffffff",
        "error-container": "#ffdad6",
        "primary-fixed": "#a4f2d2",
        "primary-fixed-dim": "#89d6b7",
        "on-primary-fixed": "#002116",
        "on-primary-fixed-variant": "#00513c",
        "secondary-fixed": "#d2e7df",
        "secondary-fixed-dim": "#b6cbc3",
        "on-secondary-fixed": "#0c1f1a",
        "on-secondary-fixed-variant": "#374b44",
        "tertiary-fixed": "#8cf6d3",
        "tertiary-fixed-dim": "#6fd9b8",
        "on-tertiary-fixed": "#002118",
        "on-tertiary-fixed-variant": "#00513f",
        "background": "#f7f9ff",
        "on-background": "#121d26",
        "brand-green": "#176B52",
        "brand-mint": "#DDF3EA"
      },
      borderRadius: {
        "sm": "0.25rem",
        "DEFAULT": "0.5rem",
        "md": "0.75rem",
        "lg": "1rem",
        "xl": "1.5rem",
        "20px": "20px",
        "full": "9999px"
      },
      spacing: {
        "base": "8px",
        "xs": "4px",
        "sm": "12px",
        "md": "24px",
        "lg": "48px",
        "xl": "80px",
        "gutter": "24px",
        "margin-mobile": "16px",
        "margin-desktop": "40px"
      },
      fontFamily: {
        "sans": ["Manrope", "sans-serif"],
        "display-lg": ["Manrope", "sans-serif"],
        "headline-lg": ["Manrope", "sans-serif"],
        "headline-md": ["Manrope", "sans-serif"],
        "body-lg": ["Manrope", "sans-serif"],
        "body-md": ["Manrope", "sans-serif"],
        "label-md": ["Manrope", "sans-serif"],
        "label-sm": ["Manrope", "sans-serif"]
      },
      boxShadow: {
        "ambient": "0px 4px 20px rgba(23, 107, 82, 0.06)",
        "elevated": "0px 12px 32px rgba(31, 41, 51, 0.10)",
        "ambient-hover": "0px 8px 24px rgba(23, 107, 82, 0.12)"
      }
    },
  },
  plugins: [],
}
